stages:
  - build
  - test
  - deploy
  - post-deploy-test

variables:
  DOTNET_VERSION: "6.0"
  MY_WORD: "something"
  S3_BUCKET: "brenda-qa"

before_script:
  - apt-get update -y
  - apt-get install -y wget
  - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - apt-get update -y
  - apt-get install -y dotnet-sdk-$DOTNET_VERSION

build:
  stage: build
  script:
    - dotnet clean
    - dotnet restore
    - dotnet build --configuration Release
  artifacts:
    paths:
      - bin/

test:
  stage: test
  script:
    - dotnet test --configuration Release

deploy:
  stage: deploy
  script:
    - echo "Installing git if not present..."
    - apt-get update -y
    - apt-get install -y git
    - echo "Configuring git user..."
    - git config --global user.email "brenda.magana@armur.femsa.com"
    - git config --global user.name "BreMG24"
    - echo "Cloning from GitLab..."
    - git clone "https://oauth2:${GITLAB_TOKEN}@gitlab.com/Proyecto%20Externos/Proyecto%20Externo%201/laboratorio.git"
    - cd laboratorio
    - echo "Adding GitHub remote..."
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/BreMG24/MockupBrenda.git
    - echo "Pushing to GitHub..."
    - git push github main


    - git push origin main
  environment:
    name: production
  only:
    - main


#url: https://github.com/BreMG24/MockupBrenda.git


post-deploy-test:
  stage: post-deploy-test
  script:
    - echo "Running post-deployment tests..."
    # Aquí puedes agregar comandos para ejecutar tus pruebas en producción
    - curl -f http://production_server_url/health || exit 1
    - dotnet test --configuration Release --filter "Category=PostDeploy"
  environment:
    name: production
  only:
    - master
  #when: manual
